CREATE TABLE "TERMTOOL"."BULK_CANVAS_COURSE_CRTN_JOB"
  (
    "ID" NUMBER(11,0) NOT NULL ENABLE,
    "SCHOOL_ID" NVARCHAR2(10),
    "SIS_TERM_ID" NUMBER(11,0) NOT NULL ENABLE,
    "STATUS" NVARCHAR2(20),
    "CREATED_AT" TIMESTAMP (6) NOT NULL ENABLE,
    "CREATED_BY_USER_ID" NVARCHAR2(20),
    "UPDATED_AT" TIMESTAMP (6) NOT NULL ENABLE,

    PRIMARY KEY ("ID") ENABLE

  );



CREATE INDEX "TERMTOOL"."BULK_CC_CRTN_JOB_IDX1" ON "TERMTOOL"."BULK_CANVAS_COURSE_CRTN_JOB"
  (
    "ID"
  ) ;



CREATE SEQUENCE "TERMTOOL"."BULK_CC_CRTN_JOB_SQ" MINVALUE 1 MAXVALUE 9999999999999999
INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE ;


CREATE OR REPLACE TRIGGER "TERMTOOL"."BULK_CC_CRTN_JOB_TR"
BEFORE INSERT ON "BULK_CANVAS_COURSE_CRTN_JOB"
FOR EACH ROW WHEN (new."ID" IS NULL)
BEGIN
  SELECT "BULK_CC_CRTN_JOB_SQ".nextval INTO :new."ID" FROM dual;
END;

ALTER TRIGGER "TERMTOOL"."BULK_CC_CRTN_JOB_TR" ENABLE;


-- ADD foreign key BULK_JOB_ID to CANVAS_CONTENT_MIGRATION_JOB
ALTER TABLE CANVAS_CONTENT_MIGRATION_JOB
  ADD BULK_JOB_ID NUMBER(11,0)

