# Generated by Django 2.2.4 on 2019-10-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_course_site_wizard', '0008_auto_20150702_1317'),
        ('canvas_course_site_wizard', '0001_squashed_0005_auto_20150528_1557'),
    ]

    operations = [
    ]
